fn main() -> Result<(), Box<dyn std::error::Error>> {
    std::process::exit(peasy::main()?)
}
